# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# complements of 'dreams of autonomy' "this zsh config is perhaps my favorite one yet." vid on yt

# export ZDOTDIR=... # if where ZSH will check for config files
export ZCFGDIR=~/.config/shell
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"  # plugin manager home
export JUNIT_HOME=/usr/share/java
export CLASSPATH=$CLASSPATH:$JUNIT_HOME/junit4.jar

# clone Zinit if it does not yet exist
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
# ZSH_THEME="afowler"
# ZSH_THEME="duellj"
# ZSH_THEME="kennethreitz"
# ZSH_THEME="lukerandall"
# ZSH_THEME="pmcgee"

# source zinit (plugin manager)
source "${ZINIT_HOME}/zinit.zsh"

zinit ice depth=1; zinit light romkatv/powerlevel10k

# adding plugins
zinit light zsh-users/zsh-syntax-highlighting
# zinit light zsh-users/zsh-completions
zinit light softmoth/zsh-vim-mode
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab # fzf for tab completions


zinit snippet OMZP::git

# load autocompletions
# autoload -U compinit && compinit

# set autosuggestion "accept" key
bindkey "^y" autosuggest-accept
bindkey "^p" history-search-backward
bindkey "^n" history-search-backward


# history
HISTSIZE=10000
HISTFILE=$ZCFGDIR/history
SAVEHIST=$HISTSIZE
HISTDUP=erase

setopt appendhistory
setopt sharehistory # common history among shells
setopt hist_ignore_space # do not add cmds prepended with space to history eg ' ls <dirname>'
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
setopt no_cdable_vars

zstyle ":completion:*" matcher-list "m:{a-z}={A-Za-z}" # smartcase for shell
zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"
zstyle ":completion:*" menu no # disable default completion menu in favor of fzf
zstyle ":fzf-tab:complete:cd:*" fzf-preview "ls --color $realpath"

alias ls="ls --color"
# check file exists, then source
[ -f "$ZCFGDIR/aliases" ] && source "$ZCFGDIR/aliases"

# eval "$(fzf --zsh)" # this can be used with an up-to-date fzf installed through package manager
# [ -f "$HOME/.fzf.zsh" ] && source "$HOME/.fzf.zsh"
# Set up fzf key bindings and fuzzy completion
# source <(fzf --zsh)





# run: `man zshoptions` to see the meaning of each option
# setopt autocd extendedglob nomatch menucomplete
# setopt interactive_comments

# unsetopt BEEP # no beeping!

eval "$(zoxide init zsh)"


[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.zsh

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
   exec sesh connect main
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
